{
 "title": "Spring Boot - Simple Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "UP targets",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "UP by instance",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 0, "w": 20, "h": 6 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "HTTP RPS (per instance)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 24, "h": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "JVM Heap used (per instance)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{area=\"heap\"})"
    }
   ]
  },
  {
   "title": "JVM Threads live (per instance)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_threads_live_threads)"
    }
   ]
  }
 ]
}